### Register Candidate
POST {{host}}/api/candidates
Content-Type: multipart/form-data; boundary=JobPortalBoundary

--JobPortalBoundary
Content-Disposition: form-data; name="firstName"

Abel
--JobPortalBoundary
Content-Disposition: form-data; name="lastName"

Kassa
--JobPortalBoundary
Content-Disposition: form-data; name="phoneNumbers"

+251911223344
--JobPortalBoundary
Content-Disposition: form-data; name="email"

abel.kassa@example.com
--JobPortalBoundary
Content-Disposition: form-data; name="password"

Abel@123
--JobPortalBoundary
Content-Disposition: form-data; name="resume"; filename="cv_1.pdf"
Content-Type: application/pdf

< ./../static/cv_1.pdf
--JobPortalBoundary--

### GET Candidates
GET {{host}}/api/candidates?firstName=
Authorization: Basic tola@gmail.com tola@123
